//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karamnov_421
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class karamnov_421Entities : DbContext
    {
        private static karamnov_421Entities _context;
        public karamnov_421Entities()
            : base("name=karamnov_421Entities")
        {
        }
        public static karamnov_421Entities GetContext()
        {
            if (_context == null)
                _context = new karamnov_421Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<User> User { get; set; }
    }
}
